Login and registration implementation
DinijaSeferovic/Auction-WebApp pull request #8
Opened 2022-08-11 09:06 UTC by DinijaSeferovic

2022-08-12 09:51 UTC, azrabalic-abh requested changes

2022-08-12 09:51 UTC, azrabalic-abh commented on frontend/src/views/Login/Login.js
> +			return false;
Wh don't you call validators only once and remember its results inside variables and reuse them?

2022-08-12 09:51 UTC, azrabalic-abh commented on frontend/src/components/Input/Input.js
> +					{label && <div className="input_field_label">{label}</div>}
I think that you can always render label above input field, if the label is present. No need for checking if input field is in form

2022-08-12 09:51 UTC, azrabalic-abh commented on frontend/src/components/Input/Input.js
> +							{error !== null && error !== "" && (
This code below is mostly related to password but we are creating generic input component here. Think some other solution. Maybe you could create PasswordInput component that would wrap existing input field, but it would contain this additional logic about password strength.

2022-08-17 15:25 UTC, mirzamesihovic-abh commented on frontend/src/components/layout/navigation/Header/Header.js
> +				{localStorage.getItem("isLoggedIn") === "true" ? (
Wouldn't it be better to use User from Context and render based on whether it is null? When you are logged in, user state should be null.

2022-08-17 15:25 UTC, mirzamesihovic-abh commented on frontend/src/utils/validator.js
> +	var result = "";
Avoid using `var` whenever possible. Switch to let.

2022-08-17 15:25 UTC, mirzamesihovic-abh commented on frontend/src/views/Login/Login.js
> +	const login = (form) => {
What happens when user refreshes the page while logged in? Does the session persist properly?

2022-08-17 15:25 UTC, mirzamesihovic-abh commented on frontend/src/views/Login/Login.js
> +		if (emailResult === "" && passwordResult === "") return true;
Always write braces for if statements.

2022-08-17 15:25 UTC, mirzamesihovic-abh commented on frontend/src/views/Login/Login.js
> +	const submit = (form) => {
Wouldn't it be better if we had structured naming for method actions such as 'handleSubmit' or 'onSubmit' as they are bound to events and are handlers?

2022-08-17 15:25 UTC, mirzamesihovic-abh commented on frontend/src/views/Registration/Registration.js
> +					</Form>
You could extract this as RegistrationForm Component

2022-08-17 15:25 UTC, mirzamesihovic-abh commented on backend/src/main/java/com/auctionapp/config/jwt/JwtTokenFilter.java
> +    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
We should have java-docs documentation for methods we are writing. Always provide documentations for methodss you write as tommorow someone else might use it or you will forget what a method did.

2022-08-19 08:26 UTC, mirzamesihovic-abh commented on backend/src/main/java/com/auctionapp/config/jwt/JwtEntryPoint.java
> +     * an AuthenticationException.
New Line

2022-08-19 08:26 UTC, mirzamesihovic-abh commented on backend/src/main/java/com/auctionapp/config/jwt/JwtTokenFilter.java
> +     * It is guaranteed to be just invoked once per request within a single request thread.
New Line

2022-08-19 08:26 UTC, mirzamesihovic-abh commented on backend/src/main/java/com/auctionapp/controllers/UserController.java
> +        if (validateData(loginRequest)!=null) { return validateData(loginRequest); }
if (validateData(loginRequest) != null) {
    return validateData(loginRequest);
}

2022-08-19 08:26 UTC, mirzamesihovic-abh commented on backend/src/main/java/com/auctionapp/controllers/UserController.java
> +        if (validateData(registrationRequest)!=null) { return validateData(registrationRequest); }
Format

2022-08-19 08:26 UTC, mirzamesihovic-abh commented on backend/src/main/java/com/auctionapp/controllers/UserController.java
>          User user = new User();
Can we create a constructor or builder instead of using all these setters?

2022-08-19 08:26 UTC, mirzamesihovic-abh commented on backend/src/main/java/com/auctionapp/controllers/UserController.java
> +        if (user==null) { return new ResponseEntity<>("User not found", HttpStatus.BAD_REQUEST); }
Format

2022-08-22 09:15 UTC, mirzamesihovic-abh approved these changes

2022-08-22 09:44 UTC, merged